export const Vocabulary = [{ "de": "schlafen", "tz": "lala", "category": "verben" },
{ "de": "aufstehen/aufwachen", "tz": "amka", "category": "verben" },
{ "de": "zähneputzen", "tz": "piga mswaki", "category": "verben" },
{ "de": "duschen", "tz": "oga", "category": "verben" },
{ "de": "anziehen", "tz": "vaa", "category": "verben" },
{ "de": "ausziehen", "tz": "vua", "category": "verben" },
{ "de": "kochen", "tz": "pika", "category": "verben" },
{ "de": "trinken", "tz": "kunyua", "category": "verben" },
{ "de": "essen", "tz": "kula", "category": "verben" },
{ "de": "lesen, lernen", "tz": "soma", "category": "verben" },
{ "de": "schreiben", "tz": "andika", "category": "verben" },
{ "de": "zuhören", "tz": "sikiliza", "category": "verben" },
{ "de": "reden, quatschen", "tz": "zungumza", "category": "verben" },
{ "de": "anschauen", "tz": "angalia", "category": "verben" },
{ "de": "weinen", "tz": "lia", "category": "verben" },
{ "de": "telephonieren", "tz": "piga simu", "category": "verben" },
{ "de": "photographieren", "tz": "piga picha", "category": "verben" },
{ "de": "bügeln", "tz": "piga pasi", "category": "verben" },
{ "de": "waschen (klamotten)", "tz": "fua", "category": "verben" },
{ "de": "spielen, tanzen", "tz": "cheza", "category": "verben" },
{ "de": "fahren", "tz": "endesha", "category": "verben" },
{ "de": "kaufen", "tz": "nunua", "category": "verben" },
{ "de": "verkaufen", "tz": "uza", "category": "verben" },
{ "de": "bezahlen", "tz": "lipa", "category": "verben" },
{ "de": "denken", "tz": "fikiri", "category": "verben" },
{ "de": "verbleiben, sitzen", "tz": "kaa", "category": "verben" },
{ "de": "herkommen, aus ... kommen", "tz": "toka", "category": "verben" },
{ "de": "heißen", "tz": "itwa", "category": "verben" },
{ "de": "kommen", "tz": "kuja", "category": "verben" },
{ "de": "gehen, sich fortbewegen", "tz": "enda", "category": "verben" },
{ "de": "zurückkommen", "tz": "rudi", "category": "verben" },
{ "de": "warten", "tz": "subiri", "category": "verben" },
{ "de": "verlassen", "tz": "ondoka", "category": "verben" },
{ "de": "unterrichten", "tz": "fundisha", "category": "verben" },
{ "de": "lernen", "tz": "jifunza", "category": "verben" },
{ "de": "können", "tz": "weza", "category": "verben" },
{ "de": "verstehen", "tz": "elewa", "category": "verben" },
{ "de": "wissen", "tz": "jua", "category": "verben" },
{ "de": "sich verspäten", "tz": "chelewa", "category": "verben" },
{ "de": "pünktlich sein", "tz": "wahi", "category": "verben" },
{ "de": "müde sein", "tz": "choka", "category": "verben" },
{ "de": "pause machen, chillen", "tz": "pumzika", "category": "verben" },
{ "de": "wollen", "tz": "taka", "category": "verben" },
{ "de": "brauchen, müssen", "tz": "hitaji", "category": "verben" },
{ "de": "anfangen", "tz": "anza", "category": "verben" },
{ "de": "aufhören, beenden", "tz": "maliza", "category": "verben" },
{ "de": "benutzen", "tz": "tumia", "category": "verben" },
{ "de": "mögen, lieben", "tz": "penda", "category": "verben" },
{ "de": "glücklich sein, sich freuen", "tz": "furahi", "category": "verben" },
{ "de": "um etwas bitten, beten", "tz": "omba", "category": "verben" },
{ "de": "helfen", "tz": "saidia", "category": "verben" },
{ "de": "sprechen", "tz": "ongea", "category": "verben" },
{ "de": "schließen, verpacken", "tz": "funga", "category": "verben" },
{ "de": "öffnen", "tz": "fungua", "category": "verben" },
{ "de": "bringen, mitbringen", "tz": "peleka", "category": "verben" },
{ "de": "herbringen", "tz": "leta", "category": "verben" },
{ "de": "reinstecken, hinstellen", "tz": "weka", "category": "verben" },
{ "de": "versuchen, probieren, in Versuchung führen", "tz": "jaribu", "category": "verben" },
{ "de": "rennen", "tz": "kimbia", "category": "verben" },
{ "de": "vorbeigehen, ausweichen", "tz": "pita", "category": "verben" },
{ "de": "ankommen", "tz": "fika", "category": "verben" },
{ "de": "sagen", "tz": "sema", "category": "verben" },
{ "de": "schlagen", "tz": "piga", "category": "verben" },
{ "de": "sich beruhigen, runterkommen", "tz": "tulia", "category": "verben" },
{ "de": "singen", "tz": "imba", "category": "verben" },
{ "de": "addieren", "tz": "jumlisha", "category": "verben" },
{ "de": "subtrahieren, wegmachen, abheben", "tz": "toa", "category": "verben" },
{ "de": "aufteilen, teilen", "tz": "gawanya", "category": "verben" },
{ "de": "multiplizieren", "tz": "zidisha", "category": "verben" },
{ "de": "fragen", "tz": "uliza", "category": "verben" },
{ "de": "streicheln", "tz": "bembeleza", "category": "verben" },
{ "de": "kratzen", "tz": "kuna", "category": "verben" },
{ "de": "lachen", "tz": "cheka", "category": "verben" },
{ "de": "sein", "tz": "kuwa", "category": "verben" },
{ "de": "sich erinnern (auch: vermissen)", "tz": "kumbuka", "category": "verben" },
{ "de": "geboren sein", "tz": "zaliwa", "category": "verben" },
{ "de": "bekommen, finden", "tz": "pata", "category": "verben" },
{ "de": "besuchen", "tz": "tembelea", "category": "verben" },
{ "de": "verringern", "tz": "punguza", "category": "verben" },
{ "de": "sagen", "tz": "ambia", "category": "verben" },
{ "de": "zurückgeben/-bringen", "tz": "rudisha", "category": "verben" },
{ "de": "vergessen", "tz": "sahau", "category": "verben" },
{ "de": "sich treffen mit", "tz": "kutana na", "category": "verben" },
{ "de": "weitermachen", "tz": "endelea", "category": "verben" },
{ "de": "anstreichen, malen", "tz": "paka", "category": "verben" },
{ "de": "machen, basteln, reparieren", "tz": "tengeneza", "category": "verben" },
{ "de": "zeichnen", "tz": "chora", "category": "verben" },
{ "de": "stinken", "tz": "nuka", "category": "verben" },
{ "de": "duften", "tz": "nukia", "category": "verben" },
{ "de": "scherzen", "tz": "zingua", "category": "verben" },
{ "de": "halten (zB. shika mkono)", "tz": "shika", "category": "verben" },
{ "de": "kaputt sein", "tz": "vunjika", "category": "verben" },
{ "de": "krank sein, weh tun", "tz": "umwa", "category": "verben" },
{ "de": "schneiden, sägen", "tz": "kata", "category": "verben" },
{ "de": "reparieren", "tz": "rekabisha", "category": "verben" },
{ "de": "ziehen", "tz": "vuta", "category": "verben" },
{ "de": "drücken", "tz": "sukuma", "category": "verben" },
{ "de": "ausdrucken", "tz": "koprinti", "category": "verben" },
{ "de": "nörgeln, sich beschweren", "tz": "lalamika", "category": "verben" },
{ "de": "zeigen", "tz": "onyesha", "category": "verben" },
{ "de": "betrunken sein", "tz": "lewa", "category": "verben" },
{ "de": "(weibl.) verheiratet sein", "tz": "olewa", "category": "verben" },
{ "de": "(männl.) verheiratet sein", "tz": "oa", "category": "verben" },
{ "de": "sich fürchten, Angst haben", "tz": "ogopa", "category": "verben" },
{ "de": "ausgehen, leer sein", "tz": "isha", "category": "verben" },
{ "de": "aufhören, stoppen", "tz": "acha", "category": "verben" },
{ "de": "verbleiben, sich aufhalten", "tz": "baki", "category": "verben" },
{ "de": "sich umdrehen (geuka nyuma)", "tz": "geuka", "category": "verben" },
{ "de": "sich verlieren, verloren sein", "tz": "potea", "category": "verben" },
{ "de": "wütend/sauer sein", "tz": "kasiriki", "category": "verben" },
{ "de": "stehen, stoppen", "tz": "simama", "category": "verben" },
{ "de": "satt sein", "tz": "shiba", "category": "verben" },
{ "de": "hunger haben", "tz": "jaa", "category": "verben" },
{ "de": "sich vertun/falsch sein", "tz": "kosa", "category": "verben" },
{ "de": "antworten", "tz": "jibu", "category": "verben" },
{ "de": "grüßen", "tz": "salimia", "category": "verben" },
{ "de": "sichergehen", "tz": "hakikisha", "category": "verben" },
{ "de": "einfügen", "tz": "ingiza", "category": "verben" },
{ "de": "einschenken", "tz": "mimina", "category": "verben" },
{ "de": "senden", "tz": "tumia", "category": "verben" },
{ "de": "jmd. etwas wünschen", "tz": "takia", "category": "verben" },
{ "de": "vorbereiten", "tz": "andaa", "category": "verben" },
{ "de": "schälen", "tz": "menya", "category": "verben" },
{ "de": "tragen", "tz": "beba", "category": "verben" },
{ "de": "backen", "tz": "oka", "category": "verben" },
{ "de": "nähen", "tz": "shona", "category": "verben" },
{ "de": "fegen", "tz": "fagia", "category": "verben" },
{ "de": "erhalten", "tz": "pokea", "category": "verben" },
{ "de": "abreißen, zerstören", "tz": "bomoa", "category": "verben" },
{ "de": "akzeptieren, zustimmen", "tz": "kubali", "category": "verben" },
{ "de": "zerstören", "tz": "haribu", "category": "verben" },
{ "de": "zählen", "tz": "hesabu", "category": "verben" },
{ "de": "dekorieren", "tz": "pamba", "category": "verben" },
{ "de": "laut sein, Krach machen", "tz": "piga kilele", "category": "verben" },
{ "de": "mieten", "tz": "panga", "category": "verben" },
{ "de": "aufwecken", "tz": "amsha", "category": "verben" },
{ "de": "jemanden beklauen", "tz": "iba", "category": "verben" },
{ "de": "stören", "tz": "sumbua", "category": "verben" },
{ "de": "ändern", "tz": "badilisha", "category": "verben" },
{ "de": "rufen", "tz": "ita", "category": "verben" },
{ "de": "Essen anrichten, servieren", "tz": "pakua", "category": "verben" },
{ "de": "retten", "tz": "okoa", "category": "verben" },
{ "de": "betrügen", "tz": "saliti", "category": "verben" },
{ "de": "kreuzigen", "tz": "sulubu", "category": "verben" },
{ "de": "verlieren, besiegt sein", "tz": "shindwa", "category": "verben" },
{ "de": "genesen", "tz": "pona", "category": "verben" },
{ "de": "betrunken sein", "tz": "lewa", "category": "verben" },
{ "de": "entscheiden", "tz": "amoa", "category": "verben" },
{ "de": "bestrafen", "tz": "adhibu", "category": "verben" },
{ "de": "(ein Ding) bewegen, verrücken", "tz": "zogesa", "category": "verben" },
{ "de": "(ein Mensch) bewegen, verrücken, aufrücken", "tz": "zogea", "category": "verben" },
{ "de": "waschen (Geschirr)", "tz": "osha", "category": "verben" },
{ "de": "löschen, radieren", "tz": "futa", "category": "verben" },
{ "de": "etwas lieber mögen", "tz": "pendelea", "category": "verben" },
{ "de": "traurig sein", "tz": "sikitika", "category": "verben" },
{ "de": "einladen", "tz": "alika", "category": "verben" },
{ "de": "verbrennen", "tz": "ungua", "category": "verben" },
{ "de": "glauben", "tz": "amini", "category": "verben" },
{ "de": "kleben", "tz": "gundi", "category": "verben" },
{ "de": "träumen", "tz": "ota", "category": "verben" },
{ "de": "hereinkommen", "tz": "ingia", "category": "verben" },
{ "de": "sicher sein", "tz": "wakika", "category": "verben" },
{ "de": "sich bewegen", "tz": "hama", "category": "verben" },
{ "de": "etwas bewegen", "tz": "hamisha", "category": "verben" },
{ "de": "aussteigen", "tz": "shuka", "category": "verben" },
{ "de": "jemanden aussteigen lassen/runterlassen", "tz": "shusha", "category": "verben" },
{ "de": "runterfallen lassen", "tz": "dondosha, angusha", "category": "verben" },
{ "de": "korrigieren", "tz": "sahihisha", "category": "verben" },
{ "de": "folgen", "tz": "fuata", "category": "verben" },
{ "de": "überrascht/geschockt sein", "tz": "shangaa", "category": "verben" },
{ "de": "weniger sein, verringert werden", "tz": "pungua", "category": "verben" },
{ "de": "ablehnen, verneinen", "tz": "kataa", "category": "verben" },
{ "de": "anschalten", "tz": "washa", "category": "verben" },
{ "de": "zwingen", "tz": "lazimisha", "category": "verben" },
{ "de": "schmelzen", "tz": "yeyuka", "category": "verben" },
{ "de": "anders sein, sich verändert haben", "tz": "badilika", "category": "verben" },
{ "de": "fallen", "tz": "anguka", "category": "verben" },
{ "de": "die Brust geben", "tz": "nyonya", "category": "verben" },
{ "de": "riechen", "tz": "nusa", "category": "verben" },
{ "de": "informieren", "tz": "julisha", "category": "verben" },
{ "de": "gekocht werden", "tz": "chemka", "category": "verben" },
{ "de": "etwas zum kochen bringen", "tz": "chemsha", "category": "verben" },
{ "de": "bilden, lehren", "tz": "elimisha", "category": "verben" },
{ "de": "mästen, fett machen", "tz": "nenepesha", "category": "verben" },
{ "de": "verkürzen", "tz": "fupisha", "category": "verben" },
{ "de": "etwas gefährlich machen", "tz": "hatarisha", "category": "verben" },
{ "de": "lügen", "tz": "ongo", "category": "verben" },
{ "de": "reisen", "tz": "safiri", "category": "verben" },
{ "de": "aufräumen, säubern", "tz": "safisha", "category": "verben" },
{ "de": "töten", "tz": "ua", "category": "verben" },
{ "de": "beißen", "tz": "uma", "category": "verben" },
{ "de": "sterben", "tz": "kufa", "category": "verben" },
{ "de": "suchen", "tz": "tafuta", "category": "verben" },
{ "de": "flechten", "tz": "suka", "category": "verben" },
{ "de": "vereinfachen (mathematisch)", "tz": "rakisisha", "category": "verben" },
{ "de": "nennen", "tz": "taja", "category": "verben" },
{ "de": "ausschalten", "tz": "sima", "category": "verben" },
{ "de": "ausleihen", "tz": "azima", "category": "verben" },
{ "de": "geben", "tz": "pa", "category": "verben" },
{ "de": "hungrig sein", "tz": "nja", "category": "verben" },
{ "de": "feiern", "tz": "sherekia", "category": "verben" },
{ "de": "lang,hoch", "tz": "refu", "category": "adjektive" },
{ "de": "klein", "tz": "dogo", "category": "adjektive" },
{ "de": "dreckig", "tz": "chafu", "category": "adjektive" },
{ "de": "schön, gut", "tz": "zuri", "category": "adjektive" },
{ "de": "fett", "tz": "nene", "category": "adjektive" },
{ "de": "bitter, sauer", "tz": "chungu", "category": "adjektive" },
{ "de": "wie viel?", "tz": "ngapi", "category": "adjektive" },
{ "de": "neu", "tz": "pya", "category": "adjektive" },
{ "de": "faul", "tz": "vivu", "category": "adjektive" },
{ "de": "kaputt, verrottet", "tz": "bovu", "category": "adjektive" },
{ "de": "schwer", "tz": "zito", "category": "adjektive" },
{ "de": "weit", "tz": "pana", "category": "adjektive" },
{ "de": "vollständig, heile", "tz": "zima", "category": "adjektive" },
{ "de": "kurz, klein", "tz": "fupi", "category": "adjektive" },
{ "de": "groß", "tz": "kubwa", "category": "adjektive" },
{ "de": "sauber", "tz": "safi", "category": "adjektive" },
{ "de": "schlecht, hässlich", "tz": "baya", "category": "adjektive" },
{ "de": "lecker, süß", "tz": "tamu", "category": "adjektive" },
{ "de": "stark, streng, scharf", "tz": "kali", "category": "adjektive" },
{ "de": "neu (Menschen: Gäste)", "tz": "geni", "category": "adjektive" },
{ "de": "wenige", "tz": "chache", "category": "adjektive" },
{ "de": "hart, schwer", "tz": "gumu", "category": "adjektive" },
{ "de": "leer", "tz": "tupu", "category": "adjektive" },
{ "de": "trocken, schlicht", "tz": "kavu", "category": "adjektive" },
{ "de": "Stadt", "tz": "mji", "category": "nomen" },
{ "de": "Klo, WC", "tz": "choo", "category": "nomen" },
{ "de": "Universität", "tz": "chuo", "category": "nomen" },
{ "de": "Bild", "tz": "picha", "category": "nomen" },
{ "de": "Motorrad", "tz": "piki piki", "category": "nomen" },
{ "de": "Musik", "tz": "musiki", "category": "nomen" },
{ "de": "Buch", "tz": "kitabu", "category": "nomen" },
{ "de": "Brief", "tz": "barua", "category": "nomen" },
{ "de": "Mathematik", "tz": "hisabati", "category": "nomen" },
{ "de": "Sprache", "tz": "lugha", "category": "nomen" },
{ "de": "Frage", "tz": "(ma)swali", "category": "nomen" },
{ "de": "Aufgabe", "tz": "(ma)zoezi", "category": "nomen" },
{ "de": "Anfang", "tz": "mwanza", "category": "nomen" },
{ "de": "Ende", "tz": "mwisho", "category": "nomen" },
{ "de": "Beispiel", "tz": "mfano", "category": "nomen" },
{ "de": "Land, Nation", "tz": "nchi", "category": "nomen" },
{ "de": "Baum", "tz": "mti", "category": "nomen" },
{ "de": "Spiele,Sport", "tz": "michezo", "category": "nomen" },
{ "de": "Tisch", "tz": "meza", "category": "nomen" },
{ "de": "Heft", "tz": "daftari", "category": "nomen" },
{ "de": "Hälfte", "tz": "nusu", "category": "nomen" },
{ "de": "Viertel", "tz": "robo", "category": "nomen" },
{ "de": "Uhr", "tz": "(ma)saa", "category": "nomen" },
{ "de": "Zeit", "tz": "muda", "category": "nomen" },
{ "de": "Minute", "tz": "dakika", "category": "nomen" },
{ "de": "Berg", "tz": "mlima", "category": "nomen" },
{ "de": "Haus", "tz": "nyumba", "category": "nomen" },
{ "de": "Ball/Fußball", "tz": "mpira", "category": "nomen" },
{ "de": "Kino", "tz": "sinema", "category": "nomen" },
{ "de": "Blume", "tz": "ua", "category": "nomen" },
{ "de": "Kerze", "tz": "mshumaa", "category": "nomen" },
{ "de": "Füller", "tz": "kalamu", "category": "nomen" },
{ "de": "Bleistift", "tz": "penseli", "category": "nomen" },
{ "de": "Schere", "tz": "mkasi", "category": "nomen" },
{ "de": "Zahnbürste", "tz": "mswaki", "category": "nomen" },
{ "de": "Moschee", "tz": "msikiti", "category": "nomen" },
{ "de": "Kirche", "tz": "kanisa", "category": "nomen" },
{ "de": "Unterrichtsstunde", "tz": "kipindi, leseni", "category": "nomen" },
{ "de": "Stuhl", "tz": "kiti", "category": "nomen" },
{ "de": "Bett", "tz": "kitanda", "category": "nomen" },
{ "de": "Geld", "tz": "pesa/hela", "category": "nomen" },
{ "de": "Bus", "tz": "basi", "category": "nomen" },
{ "de": "Schrank", "tz": "kabati", "category": "nomen" },
{ "de": "Eimer", "tz": "ndoo", "category": "nomen" },
{ "de": "Bügeleisen", "tz": "pasi", "category": "nomen" },
{ "de": "Tür", "tz": "mlango", "category": "nomen" },
{ "de": "Fenster", "tz": "dirisha", "category": "nomen" },
{ "de": "Treppen", "tz": "ngazi", "category": "nomen" },
{ "de": "Badezimmer", "tz": "bafu", "category": "nomen" },
{ "de": "Auto", "tz": "(ma)gari", "category": "nomen" },
{ "de": "Korb", "tz": "kikapu", "category": "nomen" },
{ "de": "Basketball", "tz": "mpira wa kikapu", "category": "nomen" },
{ "de": "Koffer", "tz": "begi", "category": "nomen" },
{ "de": "Fahrrad", "tz": "baisikeli", "category": "nomen" },
{ "de": "Seite", "tz": "ukurasa", "category": "nomen" },
{ "de": "Zauberstab", "tz": "fimbo ya uchawi", "category": "nomen" },
{ "de": "Magie", "tz": "uchawi", "category": "nomen" },
{ "de": "SIM Karte", "tz": "laini", "category": "nomen" },
{ "de": "Kleidung", "tz": "nguo", "category": "nomen" },
{ "de": "TV", "tz": "TV", "category": "nomen" },
{ "de": "Ozean, Meer", "tz": "bahari", "category": "nomen" },
{ "de": "Pool / Billiard", "tz": "puru", "category": "nomen" },
{ "de": "Wort", "tz": "(ma)neno", "category": "nomen" },
{ "de": "Schule", "tz": "shule", "category": "nomen" },
{ "de": "Magier, Zauberer", "tz": "mchawi", "category": "nomen" },
{ "de": "Kartenspiel", "tz": "karata", "category": "nomen" },
{ "de": "Beutel, Geldbeutel", "tz": "pochi", "category": "nomen" },
{ "de": "Sandalen", "tz": "sendazi", "category": "nomen" },
{ "de": "Gott", "tz": "mungu", "category": "nomen" },
{ "de": "Holz", "tz": "mbao", "category": "nomen" },
{ "de": "Brett / Holzstück", "tz": "kibao", "category": "nomen" },
{ "de": "Feuer", "tz": "moto", "category": "nomen" },
{ "de": "Medizin", "tz": "dawa", "category": "nomen" },
{ "de": "(Stadt)viertel, Bruchteil,Teil", "tz": "sehemu", "category": "nomen" },
{ "de": "Sammlung", "tz": "usahihi", "category": "nomen" },
{ "de": "Winkel", "tz": "pembe", "category": "nomen" },
{ "de": "Summe", "tz": "jumla", "category": "nomen" },
{ "de": "Wert (mathematisch)", "tz": "themani", "category": "nomen" },
{ "de": "Gruppe", "tz": "kundi", "category": "nomen" },
{ "de": "Lärm", "tz": "kelele", "category": "nomen" },
{ "de": "Radio", "tz": "redio", "category": "nomen" },
{ "de": "Papier/Blatt", "tz": "karatasi", "category": "nomen" },
{ "de": "Problem", "tz": "shida", "category": "nomen" },
{ "de": "Liebe", "tz": "upendo", "category": "nomen" },
{ "de": "Studien, Fächer", "tz": "masomo", "category": "nomen" },
{ "de": "Weg", "tz": "njia", "category": "nomen" },
{ "de": "Dorf", "tz": "kijiji", "category": "nomen" },
{ "de": "Frankreich", "tz": "ufaranza", "category": "nomen" },
{ "de": "Deutschland", "tz": "ujerumani", "category": "nomen" },
{ "de": "Gehalt", "tz": "mshahara", "category": "nomen" },
{ "de": "Fluss", "tz": "mto", "category": "nomen" },
{ "de": "Gegenteil", "tz": "kinyume", "category": "nomen" },
{ "de": "Zimmer", "tz": "chumba", "category": "nomen" },
{ "de": "Ort", "tz": "mahali", "category": "nomen" },
{ "de": "Vergangenheit", "tz": "zamani", "category": "nomen" },
{ "de": "Wand", "tz": "ukuta", "category": "nomen" },
{ "de": "See", "tz": "siwa", "category": "nomen" },
{ "de": "Licht/Lampe", "tz": "taa", "category": "nomen" },
{ "de": "Schnee", "tz": "thelugi / barafu", "category": "nomen" },
{ "de": "Wald", "tz": "mzitu", "category": "nomen" },
{ "de": "Teekessel", "tz": "(ma)birika", "category": "nomen" },
{ "de": "Gepäck", "tz": "mzigo", "category": "nomen" },
{ "de": "Farm", "tz": "shambaa", "category": "nomen" },
{ "de": "Region", "tz": "mkoa", "category": "nomen" },
{ "de": "Gemeinschaft, Gesellschaft", "tz": "jamii", "category": "nomen" },
{ "de": "HIV/AIDS", "tz": "ukimwi", "category": "nomen" },
{ "de": "Krankheit", "tz": "ugonjwa", "category": "nomen" },
{ "de": "Kugelschreiber", "tz": "peni", "category": "nomen" },
{ "de": "Weihnachten", "tz": "krismasi", "category": "nomen" },
{ "de": "Müll", "tz": "takataka", "category": "nomen" },
{ "de": "Sternschnuppe", "tz": "kimondo", "category": "nomen" },
{ "de": "Schmerzen", "tz": "maumivu", "category": "nomen" },
{ "de": "Stern", "tz": "nyota", "category": "nomen" },
{ "de": "Welt, Erde", "tz": "dunia", "category": "nomen" },
{ "de": "Geburtstag", "tz": "siku ya kuzaliwa", "category": "nomen" },
{ "de": "Riß", "tz": "nyuta", "category": "nomen" },
{ "de": "Brücke", "tz": "(ma)daraja", "category": "nomen" },
{ "de": "Politik", "tz": "siasa", "category": "nomen" },
{ "de": "Besen", "tz": "ufagio", "category": "nomen" },
{ "de": "Chance", "tz": "nafassi", "category": "nomen" },
{ "de": "Lüge", "tz": "uongo", "category": "nomen" },
{ "de": "Gift", "tz": "sumu", "category": "nomen" },
{ "de": "Schotterstraße", "tz": "barabara ya vumbi", "category": "nomen" },
{ "de": "Hochzeit", "tz": "harusi", "category": "nomen" },
{ "de": "Beerdigung", "tz": "msiba", "category": "nomen" },
{ "de": "Stein", "tz": "jiwe", "category": "nomen" },
{ "de": "Geschichte, Erzählung", "tz": "hadithi", "category": "nomen" },
{ "de": "Regel, Gesetz", "tz": "sheria", "category": "nomen" },
{ "de": "Test, Examen", "tz": "mithiami", "category": "nomen" },
{ "de": "Schwangerschaft", "tz": "mimba", "category": "nomen" },
{ "de": "Matratze", "tz": "(ma)godoro", "category": "nomen" },
{ "de": "Geschirr", "tz": "vyombo", "category": "nomen" },
{ "de": "Abkürzung", "tz": "kifupi", "category": "nomen" },
{ "de": "Handlung, Tätigkeit", "tz": "kitendo", "category": "nomen" },
{ "de": "Stacheln", "tz": "miba", "category": "nomen" },
{ "de": "Traum", "tz": "ndoto", "category": "nomen" },
{ "de": "Stadium", "tz": "jukwaa", "category": "nomen" },
{ "de": "Dreck", "tz": "uchafu", "category": "nomen" },
{ "de": "Wasserfall", "tz": "maporomoko ya maji", "category": "nomen" },
{ "de": "Angler, Fischer", "tz": "mvuvi", "category": "nomen" },
{ "de": "Kokospalme", "tz": "mnazi", "category": "nomen" },
{ "de": "Küste", "tz": "pwani", "category": "nomen" },
{ "de": "Feier", "tz": "sherehe", "category": "nomen" },
{ "de": "Boden, Erde", "tz": "ardhi", "category": "nomen" },
{ "de": "Höhle", "tz": "shimo", "category": "nomen" },
{ "de": "Glitter", "tz": "vinao", "category": "nomen" },
{ "de": "Gewürze", "tz": "viungu", "category": "nomen" },
{ "de": "Bevölkerung, Population", "tz": "msongamano", "category": "nomen" },
{ "de": "Flagge", "tz": "bendera", "category": "nomen" },
{ "de": "Pflanzen, Angebautes", "tz": "mazao", "category": "nomen" },
{ "de": "Faden", "tz": "uzi", "category": "nomen" },
{ "de": "Auge", "tz": "jicho - macho", "category": "körperteile" },
{ "de": "Bart", "tz": "ndevu", "category": "körperteile" },
{ "de": "Mund", "tz": "mdomo", "category": "körperteile" },
{ "de": "Nase", "tz": "pua", "category": "körperteile" },
{ "de": "Gesicht", "tz": "sura/uso", "category": "körperteile" },
{ "de": "Kopf", "tz": "kichwa", "category": "körperteile" },
{ "de": "Haare", "tz": "nywele", "category": "körperteile" },
{ "de": "Gehirn", "tz": "ubongo", "category": "körperteile" },
{ "de": "Ohr", "tz": "sikio", "category": "körperteile" },
{ "de": "Backe", "tz": "shavu", "category": "körperteile" },
{ "de": "Rücken", "tz": "mgongo", "category": "körperteile" },
{ "de": "Herz", "tz": "moyo", "category": "körperteile" },
{ "de": "Hals", "tz": "shingo", "category": "körperteile" },
{ "de": "Haut/Leder", "tz": "ngozi", "category": "körperteile" },
{ "de": "Schulter", "tz": "bega", "category": "körperteile" },
{ "de": "Arm/Hand", "tz": "mkono", "category": "körperteile" },
{ "de": "Brust/Oberkörper", "tz": "kifua", "category": "körperteile" },
{ "de": "Ellbogen", "tz": "kiwiko", "category": "körperteile" },
{ "de": "Hüfte", "tz": "hipsi", "category": "körperteile" },
{ "de": "Bauchnabel", "tz": "kitovu", "category": "körperteile" },
{ "de": "Bauch", "tz": "tumbo", "category": "körperteile" },
{ "de": "Hintern", "tz": "tako/kalio", "category": "körperteile" },
{ "de": "Bein/Fuß", "tz": "mguu", "category": "körperteile" },
{ "de": "Knochen", "tz": "mfupa", "category": "körperteile" },
{ "de": "Finger/Zehen", "tz": "kidole", "category": "körperteile" },
{ "de": "Oberschenkel", "tz": "paja", "category": "körperteile" },
{ "de": "Blut", "tz": "damu", "category": "körperteile" },
{ "de": "Knie", "tz": "(ma)goti", "category": "körperteile" },
{ "de": "Rippen", "tz": "mbavu", "category": "körperteile" },
{ "de": "Brust", "tz": "ziwa/titi/nyunyo", "category": "körperteile" },
{ "de": "Becken", "tz": "kiuno", "category": "körperteile" },
{ "de": "Zahn", "tz": "jino", "category": "körperteile" },
{ "de": "Kinn", "tz": "kidevu", "category": "körperteile" },
{ "de": "Armband", "tz": "kacha", "category": "kleidung" },
{ "de": "Gürtel", "tz": "mkanda", "category": "kleidung" },
{ "de": "Brille", "tz": "mawani", "category": "kleidung" },
{ "de": "Ring", "tz": "pete", "category": "kleidung" },
{ "de": "Kleid", "tz": "gauni", "category": "kleidung" },
{ "de": "Hemd", "tz": "shati", "category": "kleidung" },
{ "de": "T-Shirt", "tz": "tisheti", "category": "kleidung" },
{ "de": "Hose", "tz": "suruali", "category": "kleidung" },
{ "de": "Rock", "tz": "sketi", "category": "kleidung" },
{ "de": "Jacke", "tz": "jaketi/koti", "category": "kleidung" },
{ "de": "Sweater", "tz": "sweta", "category": "kleidung" },
{ "de": "Unterwäsche", "tz": "chupi", "category": "kleidung" },
{ "de": "Schuhe", "tz": "viatu", "category": "kleidung" },
{ "de": "Hut", "tz": "kofia", "category": "kleidung" },
{ "de": "Mütze", "tz": "mzura", "category": "kleidung" },
{ "de": "Socken", "tz": "soksi", "category": "kleidung" },
{ "de": "Nashorn", "tz": "kifaru", "category": "tiere" },
{ "de": "Nilpferd", "tz": "kiboko", "category": "tiere" },
{ "de": "Hund", "tz": "mbwa", "category": "tiere" },
{ "de": "Katze", "tz": "paka", "category": "tiere" },
{ "de": "Vogel / Flugzeug", "tz": "ndege", "category": "tiere" },
{ "de": "Pferd", "tz": "farasi", "category": "tiere" },
{ "de": "Hase/Kaninchen", "tz": "sungura", "category": "tiere" },
{ "de": "Leopard", "tz": "chui", "category": "tiere" },
{ "de": "Schmetterling", "tz": "kipepeo", "category": "tiere" },
{ "de": "Elephant", "tz": "tembo", "category": "tiere" },
{ "de": "Löwe", "tz": "simba", "category": "tiere" },
{ "de": "Affe", "tz": "nyani", "category": "tiere" },
{ "de": "Schwein", "tz": "ngulule", "category": "tiere" },
{ "de": "Papagai", "tz": "kasuku", "category": "tiere" },
{ "de": "Krankenpfleger", "tz": "nesi", "category": "personen" },
{ "de": "Doktor, Artzt", "tz": "daktari", "category": "personen" },
{ "de": "Polizist", "tz": "polisi", "category": "personen" },
{ "de": "Priester", "tz": "mchungali", "category": "personen" },
{ "de": "Koch", "tz": "mpichi", "category": "personen" },
{ "de": "Schüler", "tz": "mwanafunzi", "category": "personen" },
{ "de": "Eltern", "tz": "wazazi", "category": "personen" },
{ "de": "Familie", "tz": "familia", "category": "personen" },
{ "de": "Tansanier", "tz": "watanzania", "category": "personen" },
{ "de": "Reisender, Irrender, (Weißer)", "tz": "mzungu", "category": "personen" },
{ "de": "Nachbar", "tz": "jirani", "category": "personen" },
{ "de": "Freund", "tz": "rafiki", "category": "personen" },
{ "de": "Fahrer", "tz": "dereva", "category": "personen" },
{ "de": "Präsident", "tz": "rais", "category": "personen" },
{ "de": "Polizist", "tz": "polisi/askari", "category": "personen" },
{ "de": "Doktor med.", "tz": "daktari", "category": "personen" },
{ "de": "Ehemann", "tz": "mme", "category": "personen" },
{ "de": "Mann", "tz": "mwanamme / mwanamume", "category": "personen" },
{ "de": "Ehefrau", "tz": "mke", "category": "personen" },
{ "de": "Frau", "tz": "mwanamke", "category": "personen" },
{ "de": "Mädchen", "tz": "msichana", "category": "personen" },
{ "de": "Junge", "tz": "mvulana", "category": "personen" },
{ "de": "Person", "tz": "mtu", "category": "personen" },
{ "de": "Amerikaner", "tz": "mmareani", "category": "personen" },
{ "de": "Deutscher", "tz": "mjerumani", "category": "personen" },
{ "de": "Lehrer", "tz": "mwalimu", "category": "personen" },
{ "de": "Kind", "tz": "mtoto", "category": "personen" },
{ "de": "Tourist", "tz": "mtalii", "category": "personen" },
{ "de": "Tauber", "tz": "kiziwi", "category": "personen" },
{ "de": "Blinder", "tz": "kipofu", "category": "personen" },
{ "de": "Jugendlicher", "tz": "kijana", "category": "personen" },
{ "de": "Behinderter", "tz": "kilema", "category": "personen" },
{ "de": "Alter Mann", "tz": "mzee", "category": "personen" },
{ "de": "Kranker", "tz": "mgonjwa", "category": "personen" },
{ "de": "Armer", "tz": "(ma)sikini", "category": "personen" },
{ "de": "Reicher", "tz": "(ma)tajiri", "category": "personen" },
{ "de": "Arbeiter", "tz": "mfanya kazi", "category": "personen" },
{ "de": "Bauer", "tz": "mkulima", "category": "personen" },
{ "de": "Wachmann", "tz": "mlinzi", "category": "personen" },
{ "de": "Einbrecher", "tz": "kibaka", "category": "personen" },
{ "de": "(mein) Freund, Kamerad", "tz": "mwenzangu", "category": "personen" },
{ "de": "Direktor", "tz": "mkurungenzi", "category": "personen" },
{ "de": "Schulleiter, Rektor", "tz": "mwalimu mkuu", "category": "personen" },
{ "de": "Dieb", "tz": "mwizi", "category": "personen" },
{ "de": "Boss, Chef", "tz": "bossi", "category": "personen" },
{ "de": "Anführer, Leiter", "tz": "kiongozi", "category": "personen" },
{ "de": "Restaurant", "tz": "mgahawa", "category": "essen" },
{ "de": "Ingwer", "tz": "tangawizi", "category": "essen" },
{ "de": "Geschirr", "tz": "vyombo", "category": "essen" },
{ "de": "Cashews", "tz": "korosho", "category": "essen" },
{ "de": "Erdnüsse", "tz": "karanga", "category": "essen" },
{ "de": "Saft", "tz": "juisi", "category": "essen" },
{ "de": "Tomate", "tz": "nyanya", "category": "essen" },
{ "de": "Tasse", "tz": "kikombe", "category": "essen" },
{ "de": "Gabel", "tz": "uma", "category": "essen" },
{ "de": "Messer", "tz": "kisu", "category": "essen" },
{ "de": "Alkohol", "tz": "pombe", "category": "essen" },
{ "de": "Küche / Herd / Ofen", "tz": "jiko", "category": "essen" },
{ "de": "Flasche", "tz": "chupa", "category": "essen" },
{ "de": "Kuchen", "tz": "keki", "category": "essen" },
{ "de": "Tomate", "tz": "nyanya", "category": "essen" },
{ "de": "Apfel", "tz": "epo", "category": "essen" },
{ "de": "Orange", "tz": "(ma)chungwa", "category": "essen" },
{ "de": "Ei", "tz": "(ma)yai", "category": "essen" },
{ "de": "Papaya", "tz": "papai", "category": "essen" },
{ "de": "Zwiebeln", "tz": "vitunguu", "category": "essen" },
{ "de": "Kartoffeln", "tz": "viazi", "category": "essen" },
{ "de": "Pizza", "tz": "piza", "category": "essen" },
{ "de": "Bier", "tz": "bia", "category": "essen" },
{ "de": "Tee", "tz": "chai", "category": "essen" },
{ "de": "widerliche Mais-Pampe. pfui", "tz": "Ugali", "category": "essen" },
{ "de": "Suppe", "tz": "supu", "category": "essen" },
{ "de": "Nudeln", "tz": "tambi", "category": "essen" },
{ "de": "Guaven", "tz": "mapera", "category": "essen" },
{ "de": "Pommes-Omlett", "tz": "chipsy mayai", "category": "essen" },
{ "de": "Banane", "tz": "ndizi", "category": "essen" },
{ "de": "Essen", "tz": "chakula", "category": "essen" },
{ "de": "Markt", "tz": "soko", "category": "essen" },
{ "de": "Frucht", "tz": "(ma)tunda", "category": "essen" },
{ "de": "Milch/Brüste", "tz": "maziwa", "category": "essen" },
{ "de": "Kaffee", "tz": "kahawa", "category": "essen" },
{ "de": "Fleischspieße", "tz": "mishkake", "category": "essen" },
{ "de": "Kokosnuss", "tz": "nazi", "category": "essen" },
{ "de": "Fisch", "tz": "samaki", "category": "essen" },
{ "de": "Nelken", "tz": "karafu", "category": "essen" },
{ "de": "Woche", "tz": "wiki", "category": "zeit" },
{ "de": "Datum", "tz": "tarehe", "category": "zeit" },
{ "de": "Monat", "tz": "mwezi", "category": "zeit" },
{ "de": "Jahr", "tz": "mwaka", "category": "zeit" },
{ "de": "Tag", "tz": "siku", "category": "zeit" },
{ "de": "Nacht", "tz": "usiku", "category": "zeit" },
{ "de": "Morgen", "tz": "asubuhi", "category": "zeit" },
{ "de": "Mittag/Nachmittag", "tz": "mchana", "category": "zeit" },
{ "de": "Abend", "tz": "jioni", "category": "zeit" },
{ "de": "Samstag", "tz": "jumamosi", "category": "zeit" },
{ "de": "Sonntag", "tz": "jumapili", "category": "zeit" },
{ "de": "Montag", "tz": "jumatatu", "category": "zeit" },
{ "de": "Dienstag", "tz": "jumanne", "category": "zeit" },
{ "de": "Mittwoch", "tz": "jumatano", "category": "zeit" },
{ "de": "Donnerstag", "tz": "alhamisi", "category": "zeit" },
{ "de": "Freitag", "tz": "ijumaa", "category": "zeit" },
{ "de": "über", "tz": "juu", "category": "präpositionen" },
{ "de": "unter", "tz": "chini", "category": "präpositionen" },
{ "de": "neben/nah", "tz": "karibu", "category": "präpositionen" },
{ "de": "vor", "tz": "mbele", "category": "präpositionen" },
{ "de": "hinter", "tz": "nyuma", "category": "präpositionen" },
{ "de": "fern", "tz": "mbali", "category": "präpositionen" },
{ "de": "entlang", "tz": "kando", "category": "präpositionen" },
{ "de": "drinnen", "tz": "ndani", "category": "präpositionen" },
{ "de": "draußen", "tz": "nje", "category": "präpositionen" },
{ "de": "daneben", "tz": "pembeni", "category": "präpositionen" },
{ "de": "(Wahl) zwischen", "tz": "kati ya", "category": "präpositionen" },
{ "de": "(örtlich) zwischen", "tz": "katikati", "category": "präpositionen" },
{ "de": "rechts", "tz": "kulia", "category": "präpositionen" },
{ "de": "links", "tz": "kushoto", "category": "präpositionen" },
{ "de": "geradeaus", "tz": "moja kwa moja", "category": "präpositionen" },
{ "de": "anstatt (mir)", "tz": "badala (yangu)", "category": "präpositionen" },
{ "de": "(zeitlich) danach", "tz": "baada ya", "category": "präpositionen" },
{ "de": "(zeitlich) davor", "tz": "kabla ya", "category": "präpositionen" }
]