export const Vocabulary = [{"de":"schlafen","tz":"lala","recommended":true,"category":"Verben"},
{"de":"aufstehen/aufwachen","tz":"amka","recommended":true,"category":"Verben"},
{"de":"zähneputzen","tz":"piga mswaki","recommended":false,"category":"Verben"},
{"de":"duschen","tz":"oga","recommended":true,"category":"Verben"},
{"de":"anziehen","tz":"vaa","recommended":false,"category":"Verben"},
{"de":"ausziehen","tz":"vua","recommended":false,"category":"Verben"},
{"de":"kochen","tz":"pika","recommended":true,"category":"Verben"},
{"de":"trinken","tz":"kunyua","recommended":true,"category":"Verben"},
{"de":"essen","tz":"kula","recommended":true,"category":"Verben"},
{"de":"lesen, lernen","tz":"soma","recommended":true,"category":"Verben"},
{"de":"schreiben","tz":"andika","recommended":true,"category":"Verben"},
{"de":"zuhören","tz":"sikiliza","recommended":true,"category":"Verben"},
{"de":"reden, quatschen","tz":"zungumza","recommended":false,"category":"Verben"},
{"de":"anschauen","tz":"angalia","recommended":false,"category":"Verben"},
{"de":"weinen","tz":"lia","recommended":false,"category":"Verben"},
{"de":"telephonieren","tz":"piga simu","recommended":true,"category":"Verben"},
{"de":"photographieren","tz":"piga picha","recommended":false,"category":"Verben"},
{"de":"bügeln","tz":"piga pasi","recommended":false,"category":"Verben"},
{"de":"waschen (klamotten)","tz":"fua","recommended":false,"category":"Verben"},
{"de":"spielen, tanzen","tz":"cheza","recommended":false,"category":"Verben"},
{"de":"fahren","tz":"endesha","recommended":true,"category":"Verben"},
{"de":"kaufen","tz":"nunua","recommended":true,"category":"Verben"},
{"de":"verkaufen","tz":"uza","recommended":false,"category":"Verben"},
{"de":"bezahlen","tz":"lipa","recommended":true,"category":"Verben"},
{"de":"denken","tz":"fikiri","recommended":true,"category":"Verben"},
{"de":"verbleiben, sitzen","tz":"kaa","recommended":false,"category":"Verben"},
{"de":"herkommen, aus ... kommen","tz":"toka","recommended":true,"category":"Verben"},
{"de":"heißen","tz":"itwa","recommended":true,"category":"Verben"},
{"de":"kommen","tz":"kuja","recommended":true,"category":"Verben"},
{"de":"gehen, sich fortbewegen","tz":"enda","recommended":true,"category":"Verben"},
{"de":"zurückkommen","tz":"rudi","recommended":false,"category":"Verben"},
{"de":"warten","tz":"subiri","recommended":true,"category":"Verben"},
{"de":"verlassen","tz":"ondoka","recommended":true,"category":"Verben"},
{"de":"unterrichten","tz":"fundisha","recommended":false,"category":"Verben"},
{"de":"lernen","tz":"jifunza","recommended":true,"category":"Verben"},
{"de":"können","tz":"weza","recommended":true,"category":"Verben"},
{"de":"verstehen","tz":"elewa","recommended":true,"category":"Verben"},
{"de":"wissen","tz":"jua","recommended":true,"category":"Verben"},
{"de":"sich verspäten","tz":"chelewa","recommended":true,"category":"Verben"},
{"de":"pünktlich sein","tz":"wahi","recommended":false,"category":"Verben"},
{"de":"müde sein","tz":"choka","recommended":true,"category":"Verben"},
{"de":"pause machen, chillen","tz":"pumzika","recommended":true,"category":"Verben"},
{"de":"wollen","tz":"taka","recommended":true,"category":"Verben"},
{"de":"brauchen, müssen","tz":"hitaji","recommended":true,"category":"Verben"},
{"de":"anfangen","tz":"anza","recommended":true,"category":"Verben"},
{"de":"aufhören, beenden","tz":"maliza","recommended":true,"category":"Verben"},
{"de":"benutzen","tz":"tumia","recommended":true,"category":"Verben"},
{"de":"mögen, lieben","tz":"penda","recommended":true,"category":"Verben"},
{"de":"glücklich sein, sich freuen","tz":"furahi","recommended":true,"category":"Verben"},
{"de":"um etwas bitten, beten","tz":"omba","recommended":true,"category":"Verben"},
{"de":"helfen","tz":"saidia","recommended":true,"category":"Verben"},
{"de":"sprechen","tz":"ongea","recommended":true,"category":"Verben"},
{"de":"schließen, verpacken","tz":"funga","recommended":false,"category":"Verben"},
{"de":"öffnen","tz":"fungua","recommended":false,"category":"Verben"},
{"de":"bringen, mitbringen","tz":"peleka","recommended":false,"category":"Verben"},
{"de":"herbringen","tz":"leta","recommended":false,"category":"Verben"},
{"de":"reinstecken, hinstellen","tz":"weka","recommended":true,"category":"Verben"},
{"de":"versuchen, probieren, in Versuchung führen","tz":"jaribu","recommended":true,"category":"Verben"},
{"de":"rennen","tz":"kimbia","recommended":false,"category":"Verben"},
{"de":"vorbeigehen, ausweichen","tz":"pita","recommended":false,"category":"Verben"},
{"de":"ankommen","tz":"fika","recommended":false,"category":"Verben"},
{"de":"sagen","tz":"sema","recommended":true,"category":"Verben"},
{"de":"schlagen","tz":"piga","recommended":false,"category":"Verben"},
{"de":"sich beruhigen, runterkommen","tz":"tulia","recommended":false,"category":"Verben"},
{"de":"singen","tz":"imba","recommended":false,"category":"Verben"},
{"de":"addieren","tz":"jumlisha","recommended":false,"category":"Verben"},
{"de":"subtrahieren, wegmachen, abheben","tz":"toa","recommended":false,"category":"Verben"},
{"de":"aufteilen, teilen","tz":"gawanya","recommended":false,"category":"Verben"},
{"de":"multiplizieren","tz":"zidisha","recommended":false,"category":"Verben"},
{"de":"fragen","tz":"uliza","recommended":false,"category":"Verben"},
{"de":"streicheln","tz":"bembeleza","recommended":false,"category":"Verben"},
{"de":"kratzen","tz":"kuna","recommended":false,"category":"Verben"},
{"de":"lachen","tz":"cheka","recommended":false,"category":"Verben"},
{"de":"sein","tz":"kuwa","recommended":false,"category":"Verben"},
{"de":"sich erinnern (auch: vermissen)","tz":"kumbuka","recommended":false,"category":"Verben"},
{"de":"geboren sein","tz":"zaliwa","recommended":false,"category":"Verben"},
{"de":"bekommen, finden","tz":"pata","recommended":true,"category":"Verben"},
{"de":"besuchen","tz":"tembelea","recommended":false,"category":"Verben"},
{"de":"verringern","tz":"punguza","recommended":false,"category":"Verben"},
{"de":"sagen","tz":"ambia","recommended":false,"category":"Verben"},
{"de":"zurückgeben/-bringen","tz":"rudisha","recommended":false,"category":"Verben"},
{"de":"vergessen","tz":"sahau","recommended":true,"category":"Verben"},
{"de":"sich treffen mit","tz":"kutana na","recommended":false,"category":"Verben"},
{"de":"weitermachen","tz":"endelea","recommended":false,"category":"Verben"},
{"de":"anstreichen, malen","tz":"paka","recommended":false,"category":"Verben"},
{"de":"machen, basteln, reparieren","tz":"tengeneza","recommended":false,"category":"Verben"},
{"de":"zeichnen","tz":"chora","recommended":false,"category":"Verben"},
{"de":"stinken","tz":"nuka","recommended":false,"category":"Verben"},
{"de":"duften","tz":"nukia","recommended":false,"category":"Verben"},
{"de":"scherzen","tz":"zingua","recommended":false,"category":"Verben"},
{"de":"halten","tz":"shika (zB. shika mkono)","recommended":false,"category":"Verben"},
{"de":"kaputt sein","tz":"vunjika","recommended":false,"category":"Verben"},
{"de":"krank sein, weh tun","tz":"umwa","recommended":false,"category":"Verben"},
{"de":"schneiden, sägen","tz":"kata","recommended":false,"category":"Verben"},
{"de":"reparieren","tz":"rekabisha","recommended":false,"category":"Verben"},
{"de":"ziehen","tz":"vuta","recommended":false,"category":"Verben"},
{"de":"drücken","tz":"sukuma","recommended":false,"category":"Verben"},
{"de":"ausdrucken","tz":"koprinti","recommended":false,"category":"Verben"},
{"de":"nörgeln, sich beschweren","tz":"lalamika","recommended":false,"category":"Verben"},
{"de":"zeigen","tz":"onyesha","recommended":true,"category":"Verben"},
{"de":"betrunken sein","tz":"lewa","recommended":false,"category":"Verben"},
{"de":"(weibl.) verheiratet sein","tz":"olewa","recommended":false,"category":"Verben"},
{"de":"(männl.) verheiratet sein","tz":"oa","recommended":false,"category":"Verben"},
{"de":"sich fürchten, Angst haben","tz":"ogopa","recommended":false,"category":"Verben"},
{"de":"ausgehen, leer sein","tz":"isha","recommended":false,"category":"Verben"},
{"de":"aufhören, stoppen","tz":"acha","recommended":false,"category":"Verben"},
{"de":"verbleiben, sich aufhalten","tz":"baki","recommended":false,"category":"Verben"},
{"de":"sich umdrehen","tz":"geuka (geuka nyuma)","recommended":false,"category":"Verben"},
{"de":"sich verlieren, verloren sein","tz":"potea","recommended":false,"category":"Verben"},
{"de":"wütend/sauer sein","tz":"kasiriki","recommended":false,"category":"Verben"},
{"de":"stehen, stoppen","tz":"simama","recommended":false,"category":"Verben"},
{"de":"satt sein","tz":"shiba","recommended":false,"category":"Verben"},
{"de":"hunger haben","tz":"jaa","recommended":true,"category":"Verben"},
{"de":"sich vertun/falsch sein","tz":"kosa","recommended":false,"category":"Verben"},
{"de":"antworten","tz":"jibu","recommended":false,"category":"Verben"},
{"de":"grüßen","tz":"salimia","recommended":false,"category":"Verben"},
{"de":"sichergehen","tz":"hakikisha","recommended":false,"category":"Verben"},
{"de":"einfügen","tz":"ingiza","recommended":false,"category":"Verben"},
{"de":"einschenken","tz":"mimina","recommended":false,"category":"Verben"},
{"de":"senden","tz":"tumia","recommended":false,"category":"Verben"},
{"de":"jmd. etwas wünschen","tz":"takia","recommended":false,"category":"Verben"},
{"de":"vorbereiten","tz":"andaa","recommended":false,"category":"Verben"},
{"de":"schälen","tz":"menya","recommended":false,"category":"Verben"},
{"de":"tragen","tz":"beba","recommended":false,"category":"Verben"},
{"de":"backen","tz":"oka","recommended":false,"category":"Verben"},
{"de":"nähen","tz":"shona","recommended":false,"category":"Verben"},
{"de":"fegen","tz":"fagia","recommended":false,"category":"Verben"},
{"de":"erhalten","tz":"pokea","recommended":false,"category":"Verben"},
{"de":"abreißen, zerstören","tz":"bomoa","recommended":false,"category":"Verben"},
{"de":"akzeptieren, zustimmen","tz":"kubali","recommended":false,"category":"Verben"},
{"de":"zerstören","tz":"haribu","recommended":false,"category":"Verben"},
{"de":"zählen","tz":"hesabu","recommended":false,"category":"Verben"},
{"de":"dekorieren","tz":"pamba","recommended":false,"category":"Verben"},
{"de":"laut sein, Krach machen","tz":"piga kilele","recommended":false,"category":"Verben"},
{"de":"mieten","tz":"panga","recommended":false,"category":"Verben"},
{"de":"aufwecken","tz":"amsha","recommended":false,"category":"Verben"},
{"de":"jemanden beklauen","tz":"iba","recommended":false,"category":"Verben"},
{"de":"stören","tz":"sumbua","recommended":false,"category":"Verben"},
{"de":"ändern","tz":"badilisha","recommended":false,"category":"Verben"},
{"de":"rufen","tz":"ita","recommended":false,"category":"Verben"},
{"de":"Essen anrichten, servieren","tz":"pakua","recommended":false,"category":"Verben"},
{"de":"retten","tz":"okoa","recommended":false,"category":"Verben"},
{"de":"betrügen","tz":"saliti","recommended":false,"category":"Verben"},
{"de":"kreuzigen","tz":"sulubu","recommended":false,"category":"Verben"},
{"de":"verlieren, besiegt sein","tz":"shindwa","recommended":false,"category":"Verben"},
{"de":"genesen","tz":"pona","recommended":false,"category":"Verben"},
{"de":"betrunken sein","tz":"lewa","recommended":false,"category":"Verben"},
{"de":"entscheiden","tz":"amoa","recommended":false,"category":"Verben"},
{"de":"bestrafen","tz":"adhibu","recommended":false,"category":"Verben"},
{"de":"(ein Ding) bewegen, verrücken","tz":"zogesa","recommended":false,"category":"Verben"},
{"de":"(ein Mensch) bewegen, verrücken, aufrücken","tz":"zogea","recommended":false,"category":"Verben"},
{"de":"waschen (Geschirr)","tz":"osha","recommended":false,"category":"Verben"},
{"de":"löschen, radieren","tz":"futa","recommended":false,"category":"Verben"},
{"de":"etwas lieber mögen","tz":"pendelea","recommended":false,"category":"Verben"},
{"de":"traurig sein","tz":"sikitika","recommended":false,"category":"Verben"},
{"de":"einladen","tz":"alika","recommended":false,"category":"Verben"},
{"de":"verbrennen","tz":"ungua","recommended":false,"category":"Verben"},
{"de":"glauben","tz":"amini","recommended":false,"category":"Verben"},
{"de":"kleben","tz":"gundi","recommended":false,"category":"Verben"},
{"de":"träumen","tz":"ota","recommended":false,"category":"Verben"},
{"de":"hereinkommen","tz":"ingia","recommended":false,"category":"Verben"},
{"de":"sicher sein","tz":"wakika","recommended":false,"category":"Verben"},
{"de":"sich bewegen","tz":"hama","recommended":false,"category":"Verben"},
{"de":"etwas bewegen","tz":"hamisha","recommended":false,"category":"Verben"},
{"de":"aussteigen","tz":"shuka","recommended":true,"category":"Verben"},
{"de":"jemanden aussteigen lassen/runterlassen","tz":"shusha","recommended":true,"category":"Verben"},
{"de":"runterfallen lassen","tz":"dondosha, angusha","recommended":false,"category":"Verben"},
{"de":"korrigieren","tz":"sahihisha","recommended":false,"category":"Verben"},
{"de":"folgen","tz":"fuata","recommended":false,"category":"Verben"},
{"de":"überrascht/geschockt sein","tz":"shangaa","recommended":false,"category":"Verben"},
{"de":"weniger sein, verringert werden","tz":"pungua","recommended":false,"category":"Verben"},
{"de":"ablehnen, verneinen","tz":"kataa","recommended":false,"category":"Verben"},
{"de":"anschalten","tz":"washa","recommended":false,"category":"Verben"},
{"de":"zwingen","tz":"lazimisha","recommended":false,"category":"Verben"},
{"de":"schmelzen","tz":"yeyuka","recommended":false,"category":"Verben"},
{"de":"anders sein, sich verändert haben","tz":"badilika","recommended":false,"category":"Verben"},
{"de":"fallen","tz":"anguka","recommended":false,"category":"Verben"},
{"de":"die Brust geben","tz":"nyonya","recommended":false,"category":"Verben"},
{"de":"riechen","tz":"nusa","recommended":false,"category":"Verben"},
{"de":"informieren","tz":"julisha","recommended":false,"category":"Verben"},
{"de":"gekocht werden","tz":"chemka","recommended":false,"category":"Verben"},
{"de":"etwas zum kochen bringen","tz":"chemsha","recommended":false,"category":"Verben"},
{"de":"bilden, lehren","tz":"elimisha","recommended":false,"category":"Verben"},
{"de":"mästen, fett machen","tz":"nenepesha","recommended":false,"category":"Verben"},
{"de":"verkürzen","tz":"fupisha","recommended":false,"category":"Verben"},
{"de":"etwas gefährlich machen","tz":"hatarisha","recommended":false,"category":"Verben"},
{"de":"lügen","tz":"ongo","recommended":false,"category":"Verben"},
{"de":"reisen","tz":"safiri","recommended":true,"category":"Verben"},
{"de":"aufräumen, säubern","tz":"safisha","recommended":false,"category":"Verben"},
{"de":"töten","tz":"ua","recommended":false,"category":"Verben"},
{"de":"beißen","tz":"uma","recommended":false,"category":"Verben"},
{"de":"sterben","tz":"kufa","recommended":false,"category":"Verben"},
{"de":"suchen","tz":"tafuta","recommended":true,"category":"Verben"},
{"de":"flechten","tz":"suka","recommended":false,"category":"Verben"},
{"de":"vereinfachen (mathematisch)","tz":"rakisisha","recommended":false,"category":"Verben"},
{"de":"nennen","tz":"taja","recommended":false,"category":"Verben"},
{"de":"ausschalten","tz":"sima","recommended":false,"category":"Verben"},
{"de":"ausleihen","tz":"azima","recommended":false,"category":"Verben"},
{"de":"geben","tz":"pa","recommended":true,"category":"Verben"},
{"de":"hungrig sein","tz":"nja","recommended":true,"category":"Verben"},
{"de":"feiern","tz":"sherekia","recommended":false,"category":"Verben"},
{"de":"lang,hoch","tz":"refu","recommended":true,"category":"Adjektive"},
{"de":"klein","tz":"dogo","recommended":true,"category":"Adjektive"},
{"de":"dreckig","tz":"chafu","recommended":false,"category":"Adjektive"},
{"de":"schön, gut","tz":"zuri","recommended":true,"category":"Adjektive"},
{"de":"fett","tz":"nene","recommended":false,"category":"Adjektive"},
{"de":"bitter, sauer","tz":"chungu","recommended":false,"category":"Adjektive"},
{"de":"wie viel?","tz":"ngapi","recommended":true,"category":"Adjektive"},
{"de":"neu","tz":"pya","recommended":false,"category":"Adjektive"},
{"de":"faul","tz":"vivu","recommended":false,"category":"Adjektive"},
{"de":"kaputt, verrottet","tz":"bovu","recommended":false,"category":"Adjektive"},
{"de":"schwer","tz":"zito","recommended":false,"category":"Adjektive"},
{"de":"weit","tz":"pana","recommended":false,"category":"Adjektive"},
{"de":"vollständig, heile","tz":"zima","recommended":false,"category":"Adjektive"},
{"de":"kurz, klein","tz":"fupi","recommended":true,"category":"Adjektive"},
{"de":"groß","tz":"kubwa","recommended":true,"category":"Adjektive"},
{"de":"sauber","tz":"safi","recommended":true,"category":"Adjektive"},
{"de":"schlecht, hässlich","tz":"baya","recommended":true,"category":"Adjektive"},
{"de":"lecker, süß","tz":"tamu","recommended":false,"category":"Adjektive"},
{"de":"stark, streng, scharf","tz":"kali","recommended":true,"category":"Adjektive"},
{"de":"neu (Menschen: Gäste)","tz":"geni","recommended":false,"category":"Adjektive"},
{"de":"wenige","tz":"chache","recommended":true,"category":"Adjektive"},
{"de":"hart, schwer","tz":"gumu","recommended":false,"category":"Adjektive"},
{"de":"leer","tz":"tupu","recommended":false,"category":"Adjektive"},
{"de":"trocken, schlicht","tz":"kavu","recommended":false,"category":"Adjektive"},
{"de":"Stadt","tz":"mji","recommended":true,"category":"Nomen"},
{"de":"Klo, WC","tz":"choo","recommended":true,"category":"Nomen"},
{"de":"Universität","tz":"chuo","recommended":false,"category":"Nomen"},
{"de":"Bild","tz":"picha","recommended":false,"category":"Nomen"},
{"de":"Motorrad","tz":"piki piki","recommended":true,"category":"Nomen"},
{"de":"Musik","tz":"musiki","recommended":false,"category":"Nomen"},
{"de":"Buch","tz":"kitabu","recommended":true,"category":"Nomen"},
{"de":"Brief","tz":"barua","recommended":false,"category":"Nomen"},
{"de":"Mathematik","tz":"hisabati","recommended":false,"category":"Nomen"},
{"de":"Sprache","tz":"lugha","recommended":true,"category":"Nomen"},
{"de":"Frage","tz":"(ma)swali","recommended":true,"category":"Nomen"},
{"de":"Aufgabe","tz":"(ma)zoezi","recommended":true,"category":"Nomen"},
{"de":"Anfang","tz":"mwanza","recommended":false,"category":"Nomen"},
{"de":"Ende","tz":"mwisho","recommended":false,"category":"Nomen"},
{"de":"Beispiel","tz":"mfano","recommended":false,"category":"Nomen"},
{"de":"Land, Nation","tz":"nchi","recommended":true,"category":"Nomen"},
{"de":"Baum","tz":"mti","recommended":false,"category":"Nomen"},
{"de":"Spiele,Sport","tz":"michezo","recommended":false,"category":"Nomen"},
{"de":"Tisch","tz":"meza","recommended":true,"category":"Nomen"},
{"de":"Heft","tz":"daftari","recommended":false,"category":"Nomen"},
{"de":"Hälfte","tz":"nusu","recommended":false,"category":"Nomen"},
{"de":"Viertel","tz":"robo","recommended":true,"category":"Nomen"},
{"de":"Uhr","tz":"(ma)saa","recommended":true,"category":"Nomen"},
{"de":"Zeit","tz":"muda","recommended":true,"category":"Nomen"},
{"de":"Minute","tz":"dakika","recommended":true,"category":"Nomen"},
{"de":"Berg","tz":"mlima","recommended":true,"category":"Nomen"},
{"de":"Haus","tz":"nyumba","recommended":true,"category":"Nomen"},
{"de":"Ball/Fußball","tz":"mpira","recommended":false,"category":"Nomen"},
{"de":"Kino","tz":"sinema","recommended":false,"category":"Nomen"},
{"de":"Blume","tz":"ua","recommended":false,"category":"Nomen"},
{"de":"Kerze","tz":"mshumaa","recommended":false,"category":"Nomen"},
{"de":"Füller","tz":"kalamu","recommended":false,"category":"Nomen"},
{"de":"Bleistift","tz":"penseli","recommended":true,"category":"Nomen"},
{"de":"Schere","tz":"mkasi","recommended":false,"category":"Nomen"},
{"de":"Zahnbürste","tz":"mswaki","recommended":false,"category":"Nomen"},
{"de":"Moschee","tz":"msikiti","recommended":false,"category":"Nomen"},
{"de":"Kirche","tz":"kanisa","recommended":false,"category":"Nomen"},
{"de":"Unterrichtsstunde","tz":"kipindi, leseni","recommended":false,"category":"Nomen"},
{"de":"Stuhl","tz":"kiti","recommended":true,"category":"Nomen"},
{"de":"Bett","tz":"kitanda","recommended":true,"category":"Nomen"},
{"de":"Geld","tz":"pesa/hela","recommended":true,"category":"Nomen"},
{"de":"Bus","tz":"basi","recommended":true,"category":"Nomen"},
{"de":"Schrank","tz":"kabati","recommended":false,"category":"Nomen"},
{"de":"Eimer","tz":"ndoo","recommended":false,"category":"Nomen"},
{"de":"Bügeleisen","tz":"pasi","recommended":false,"category":"Nomen"},
{"de":"Tür","tz":"mlango","recommended":false,"category":"Nomen"},
{"de":"Fenster","tz":"dirisha","recommended":false,"category":"Nomen"},
{"de":"Treppen","tz":"ngazi","recommended":false,"category":"Nomen"},
{"de":"Badezimmer","tz":"bafu","recommended":false,"category":"Nomen"},
{"de":"Auto","tz":"(ma)gari","recommended":true,"category":"Nomen"},
{"de":"Korb","tz":"kikapu","recommended":false,"category":"Nomen"},
{"de":"Basketball","tz":"mpira wa kikapu","recommended":false,"category":"Nomen"},
{"de":"Koffer","tz":"begi","recommended":false,"category":"Nomen"},
{"de":"Fahrrad","tz":"baisikeli","recommended":false,"category":"Nomen"},
{"de":"Seite","tz":"ukurasa","recommended":false,"category":"Nomen"},
{"de":"Zauberstab","tz":"fimbo ya uchawi","recommended":false,"category":"Nomen"},
{"de":"Magie","tz":"uchawi","recommended":false,"category":"Nomen"},
{"de":"SIM Karte","tz":"laini","recommended":true,"category":"Nomen"},
{"de":"Kleidung","tz":"nguo","recommended":false,"category":"Nomen"},
{"de":"TV","tz":"TV","recommended":false,"category":"Nomen"},
{"de":"Ozean, Meer","tz":"bahari","recommended":true,"category":"Nomen"},
{"de":"Pool / Billiard","tz":"puru","recommended":false,"category":"Nomen"},
{"de":"Wort","tz":"(ma)neno","recommended":true,"category":"Nomen"},
{"de":"Schule","tz":"shule","recommended":true,"category":"Nomen"},
{"de":"Magier, Zauberer","tz":"mchawi","recommended":false,"category":"Nomen"},
{"de":"Kartenspiel","tz":"karata","recommended":false,"category":"Nomen"},
{"de":"Beutel, Geldbeutel","tz":"pochi","recommended":false,"category":"Nomen"},
{"de":"Sandalen","tz":"sendazi","recommended":false,"category":"Nomen"},
{"de":"Gott","tz":"mungu","recommended":false,"category":"Nomen"},
{"de":"Holz","tz":"mbao","recommended":false,"category":"Nomen"},
{"de":"Brett / Holzstück","tz":"kibao","recommended":false,"category":"Nomen"},
{"de":"Feuer","tz":"moto","recommended":false,"category":"Nomen"},
{"de":"Medizin","tz":"dawa","recommended":false,"category":"Nomen"},
{"de":"(Stadt)viertel, Bruchteil,Teil","tz":"sehemu","recommended":false,"category":"Nomen"},
{"de":"Sammlung","tz":"usahihi","recommended":false,"category":"Nomen"},
{"de":"Winkel","tz":"pembe","recommended":false,"category":"Nomen"},
{"de":"Summe","tz":"jumla","recommended":false,"category":"Nomen"},
{"de":"Wert (mathematisch)","tz":"themani","recommended":false,"category":"Nomen"},
{"de":"Gruppe","tz":"kundi","recommended":false,"category":"Nomen"},
{"de":"Lärm","tz":"kelele","recommended":false,"category":"Nomen"},
{"de":"Radio","tz":"redio","recommended":false,"category":"Nomen"},
{"de":"Papier/Blatt","tz":"karatasi","recommended":false,"category":"Nomen"},
{"de":"Problem","tz":"shida","recommended":false,"category":"Nomen"},
{"de":"Liebe","tz":"upendo","recommended":false,"category":"Nomen"},
{"de":"Studien, Fächer","tz":"masomo","recommended":false,"category":"Nomen"},
{"de":"Weg","tz":"njia","recommended":false,"category":"Nomen"},
{"de":"Dorf","tz":"kijiji","recommended":false,"category":"Nomen"},
{"de":"Frankreich","tz":"ufaranza","recommended":false,"category":"Nomen"},
{"de":"Deutschland","tz":"ujerumani","recommended":true,"category":"Nomen"},
{"de":"Gehalt","tz":"mshahara","recommended":false,"category":"Nomen"},
{"de":"Fluss","tz":"mto","recommended":false,"category":"Nomen"},
{"de":"Gegenteil","tz":"kinyume","recommended":false,"category":"Nomen"},
{"de":"Zimmer","tz":"chumba","recommended":true,"category":"Nomen"},
{"de":"Ort","tz":"mahali","recommended":false,"category":"Nomen"},
{"de":"Vergangenheit","tz":"zamani","recommended":false,"category":"Nomen"},
{"de":"Wand","tz":"ukuta","recommended":false,"category":"Nomen"},
{"de":"See","tz":"siwa","recommended":false,"category":"Nomen"},
{"de":"Licht/Lampe","tz":"taa","recommended":false,"category":"Nomen"},
{"de":"Schnee","tz":"thelugi / barafu","recommended":false,"category":"Nomen"},
{"de":"Wald","tz":"mzitu","recommended":false,"category":"Nomen"},
{"de":"Teekessel","tz":"(ma)birika","recommended":false,"category":"Nomen"},
{"de":"Gepäck","tz":"mzigo","recommended":false,"category":"Nomen"},
{"de":"Farm","tz":"shambaa","recommended":false,"category":"Nomen"},
{"de":"Region","tz":"mkoa","recommended":false,"category":"Nomen"},
{"de":"Gemeinschaft, Gesellschaft","tz":"jamii","recommended":false,"category":"Nomen"},
{"de":"HIV/AIDS","tz":"ukimwi","recommended":false,"category":"Nomen"},
{"de":"Krankheit","tz":"ugonjwa","recommended":false,"category":"Nomen"},
{"de":"Kugelschreiber","tz":"peni","recommended":false,"category":"Nomen"},
{"de":"Weihnachten","tz":"krismasi","recommended":false,"category":"Nomen"},
{"de":"Müll","tz":"takataka","recommended":false,"category":"Nomen"},
{"de":"Sternschnuppe","tz":"kimondo","recommended":false,"category":"Nomen"},
{"de":"Schmerzen","tz":"maumivu","recommended":false,"category":"Nomen"},
{"de":"Stern","tz":"nyota","recommended":false,"category":"Nomen"},
{"de":"Welt, Erde","tz":"dunia","recommended":false,"category":"Nomen"},
{"de":"Geburtstag","tz":"siku ya kuzaliwa","recommended":false,"category":"Nomen"},
{"de":"Riß","tz":"nyuta","recommended":false,"category":"Nomen"},
{"de":"Brücke","tz":"(ma)daraja","recommended":false,"category":"Nomen"},
{"de":"Politik","tz":"siasa","recommended":false,"category":"Nomen"},
{"de":"Besen","tz":"ufagio","recommended":false,"category":"Nomen"},
{"de":"Chance","tz":"nafassi","recommended":false,"category":"Nomen"},
{"de":"Lüge","tz":"uongo","recommended":false,"category":"Nomen"},
{"de":"Gift","tz":"sumu","recommended":false,"category":"Nomen"},
{"de":"Schotterstraße","tz":"barabara ya vumbi","recommended":false,"category":"Nomen"},
{"de":"Hochzeit","tz":"harusi","recommended":false,"category":"Nomen"},
{"de":"Beerdigung","tz":"msiba","recommended":false,"category":"Nomen"},
{"de":"Stein","tz":"jiwe","recommended":false,"category":"Nomen"},
{"de":"Geschichte, Erzählung","tz":"hadithi","recommended":false,"category":"Nomen"},
{"de":"Regel, Gesetz","tz":"sheria","recommended":false,"category":"Nomen"},
{"de":"Test, Examen","tz":"mithiami","recommended":false,"category":"Nomen"},
{"de":"Schwangerschaft","tz":"mimba","recommended":false,"category":"Nomen"},
{"de":"Matratze","tz":"(ma)godoro","recommended":false,"category":"Nomen"},
{"de":"Geschirr","tz":"vyombo","recommended":false,"category":"Nomen"},
{"de":"Abkürzung","tz":"kifupi","recommended":false,"category":"Nomen"},
{"de":"Handlung, Tätigkeit","tz":"kitendo","recommended":false,"category":"Nomen"},
{"de":"Stacheln","tz":"miba","recommended":false,"category":"Nomen"},
{"de":"Traum","tz":"ndoto","recommended":false,"category":"Nomen"},
{"de":"Stadium","tz":"jukwaa","recommended":false,"category":"Nomen"},
{"de":"Dreck","tz":"uchafu","recommended":false,"category":"Nomen"},
{"de":"Wasserfall","tz":"maporomoko ya maji","recommended":false,"category":"Nomen"},
{"de":"Angler, Fischer","tz":"mvuvi","recommended":false,"category":"Nomen"},
{"de":"Kokospalme","tz":"mnazi","recommended":false,"category":"Nomen"},
{"de":"Küste","tz":"pwani","recommended":false,"category":"Nomen"},
{"de":"Feier","tz":"sherehe","recommended":false,"category":"Nomen"},
{"de":"Boden, Erde","tz":"ardhi","recommended":false,"category":"Nomen"},
{"de":"Höhle","tz":"shimo","recommended":false,"category":"Nomen"},
{"de":"Glitter","tz":"vinao","recommended":false,"category":"Nomen"},
{"de":"Gewürze","tz":"viungu","recommended":false,"category":"Nomen"},
{"de":"Bevölkerung, Population","tz":"msongamano","recommended":false,"category":"Nomen"},
{"de":"Flagge","tz":"bendera","recommended":false,"category":"Nomen"},
{"de":"Pflanzen, Angebautes","tz":"mazao","recommended":false,"category":"Nomen"},
{"de":"Faden","tz":"uzi","recommended":false,"category":"Nomen"},
{"de":"Auge","tz":"jicho - macho","recommended":true,"category":"Körperteile"},
{"de":"Bart","tz":"ndevu","recommended":false,"category":"Körperteile"},
{"de":"Mund","tz":"mdomo","recommended":false,"category":"Körperteile"},
{"de":"Nase","tz":"pua","recommended":false,"category":"Körperteile"},
{"de":"Gesicht","tz":"sura/uso","recommended":false,"category":"Körperteile"},
{"de":"Kopf","tz":"kichwa","recommended":true,"category":"Körperteile"},
{"de":"Haare","tz":"nywele","recommended":false,"category":"Körperteile"},
{"de":"Gehirn","tz":"ubongo","recommended":true,"category":"Körperteile"},
{"de":"Ohr","tz":"sikio","recommended":false,"category":"Körperteile"},
{"de":"Backe","tz":"shavu","recommended":false,"category":"Körperteile"},
{"de":"Rücken","tz":"mgongo","recommended":false,"category":"Körperteile"},
{"de":"Herz","tz":"moyo","recommended":false,"category":"Körperteile"},
{"de":"Hals","tz":"shingo","recommended":false,"category":"Körperteile"},
{"de":"Haut/Leder","tz":"ngozi","recommended":false,"category":"Körperteile"},
{"de":"Schulter","tz":"bega","recommended":false,"category":"Körperteile"},
{"de":"Arm/Hand","tz":"mkono","recommended":true,"category":"Körperteile"},
{"de":"Brust/Oberkörper","tz":"kifua","recommended":false,"category":"Körperteile"},
{"de":"Ellbogen","tz":"kiwiko","recommended":false,"category":"Körperteile"},
{"de":"Hüfte","tz":"hipsi","recommended":false,"category":"Körperteile"},
{"de":"Bauchnabel","tz":"kitovu","recommended":false,"category":"Körperteile"},
{"de":"Bauch","tz":"tumbo","recommended":true,"category":"Körperteile"},
{"de":"Hintern","tz":"tako/kalio","recommended":false,"category":"Körperteile"},
{"de":"Bein/Fuß","tz":"mguu","recommended":true,"category":"Körperteile"},
{"de":"Knochen","tz":"mfupa","recommended":false,"category":"Körperteile"},
{"de":"Finger/Zehen","tz":"kidole","recommended":false,"category":"Körperteile"},
{"de":"Oberschenkel","tz":"paja","recommended":false,"category":"Körperteile"},
{"de":"Blut","tz":"damu","recommended":false,"category":"Körperteile"},
{"de":"Knie","tz":"(ma)goti","recommended":false,"category":"Körperteile"},
{"de":"Rippen","tz":"mbavu","recommended":false,"category":"Körperteile"},
{"de":"Brust","tz":"ziwa/titi/nyunyo","recommended":false,"category":"Körperteile"},
{"de":"Becken","tz":"kiuno","recommended":false,"category":"Körperteile"},
{"de":"Zahn","tz":"jino","recommended":false,"category":"Körperteile"},
{"de":"Kinn","tz":"kidevu","recommended":false,"category":"Körperteile"},
{"de":"Armband","tz":"kacha","recommended":false,"category":"Kleidung"},
{"de":"Gürtel","tz":"mkanda","recommended":false,"category":"Kleidung"},
{"de":"Brille","tz":"mawani","recommended":false,"category":"Kleidung"},
{"de":"Ring","tz":"pete","recommended":false,"category":"Kleidung"},
{"de":"Kleid","tz":"gauni","recommended":false,"category":"Kleidung"},
{"de":"Hemd","tz":"shati","recommended":false,"category":"Kleidung"},
{"de":"T-Shirt","tz":"tisheti","recommended":true,"category":"Kleidung"},
{"de":"Hose","tz":"suruali","recommended":true,"category":"Kleidung"},
{"de":"Rock","tz":"sketi","recommended":true,"category":"Kleidung"},
{"de":"Jacke","tz":"jaketi/koti","recommended":true,"category":"Kleidung"},
{"de":"Sweater","tz":"sweta","recommended":false,"category":"Kleidung"},
{"de":"Unterwäsche","tz":"chupi","recommended":false,"category":"Kleidung"},
{"de":"Schuhe","tz":"viatu","recommended":false,"category":"Kleidung"},
{"de":"Hut","tz":"kofia","recommended":false,"category":"Kleidung"},
{"de":"Mütze","tz":"mzura","recommended":false,"category":"Kleidung"},
{"de":"Socken","tz":"soksi","recommended":false,"category":"Kleidung"},
{"de":"Nashorn","tz":"kifaru","recommended":false,"category":"Tiere"},
{"de":"Nilpferd","tz":"kiboko","recommended":false,"category":"Tiere"},
{"de":"Hund","tz":"mbwa","recommended":true,"category":"Tiere"},
{"de":"Katze","tz":"paka","recommended":false,"category":"Tiere"},
{"de":"Vogel / Flugzeug","tz":"ndege","recommended":true,"category":"Tiere"},
{"de":"Pferd","tz":"farasi","recommended":false,"category":"Tiere"},
{"de":"Hase/Kaninchen","tz":"sungura","recommended":false,"category":"Tiere"},
{"de":"Leopard","tz":"chui","recommended":false,"category":"Tiere"},
{"de":"Schmetterling","tz":"kipepeo","recommended":false,"category":"Tiere"},
{"de":"Elephant","tz":"tembo","recommended":false,"category":"Tiere"},
{"de":"Löwe","tz":"simba","recommended":true,"category":"Tiere"},
{"de":"Affe","tz":"nyani","recommended":false,"category":"Tiere"},
{"de":"Schwein","tz":"ngulule","recommended":false,"category":"Tiere"},
{"de":"Papagai","tz":"kasuku","recommended":false,"category":"Tiere"},
{"de":"Krankenpfleger","tz":"nesi","recommended":false,"category":"Personen"},
{"de":"Priester","tz":"mchungali","recommended":false,"category":"Personen"},
{"de":"Koch","tz":"mpichi","recommended":false,"category":"Personen"},
{"de":"Schüler","tz":"mwanafunzi","recommended":true,"category":"Personen"},
{"de":"Eltern","tz":"wazazi","recommended":false,"category":"Personen"},
{"de":"Familie","tz":"familia","recommended":true,"category":"Personen"},
{"de":"Tansanier","tz":"watanzania","recommended":false,"category":"Personen"},
{"de":"Reisender, Irrender, (Weißer)","tz":"mzungu","recommended":false,"category":"Personen"},
{"de":"Nachbar","tz":"jirani","recommended":false,"category":"Personen"},
{"de":"Freund","tz":"rafiki","recommended":true,"category":"Personen"},
{"de":"Fahrer","tz":"dereva","recommended":true,"category":"Personen"},
{"de":"Präsident","tz":"rais","recommended":false,"category":"Personen"},
{"de":"Polizist","tz":"polisi/askari","recommended":false,"category":"Personen"},
{"de":"Doktor med.","tz":"daktari","recommended":false,"category":"Personen"},
{"de":"Ehemann","tz":"mme","recommended":false,"category":"Personen"},
{"de":"Mann","tz":"mwanamme / mwanamume","recommended":false,"category":"Personen"},
{"de":"Ehefrau","tz":"mke","recommended":false,"category":"Personen"},
{"de":"Frau","tz":"mwanamke","recommended":false,"category":"Personen"},
{"de":"Mädchen","tz":"msichana","recommended":false,"category":"Personen"},
{"de":"Junge","tz":"mvulana","recommended":false,"category":"Personen"},
{"de":"Person","tz":"mtu","recommended":false,"category":"Personen"},
{"de":"Amerikaner","tz":"mmareani","recommended":false,"category":"Personen"},
{"de":"Deutscher","tz":"mjerumani","recommended":true,"category":"Personen"},
{"de":"Lehrer","tz":"mwalimu","recommended":true,"category":"Personen"},
{"de":"Kind","tz":"mtoto","recommended":true,"category":"Personen"},
{"de":"Tourist","tz":"mtalii","recommended":false,"category":"Personen"},
{"de":"Tauber","tz":"kiziwi","recommended":false,"category":"Personen"},
{"de":"Blinder","tz":"kipofu","recommended":false,"category":"Personen"},
{"de":"Jugendlicher","tz":"kijana","recommended":false,"category":"Personen"},
{"de":"Behinderter","tz":"kilema","recommended":false,"category":"Personen"},
{"de":"Alter Mann","tz":"mzee","recommended":true,"category":"Personen"},
{"de":"Kranker","tz":"mgonjwa","recommended":false,"category":"Personen"},
{"de":"Armer","tz":"(ma)sikini","recommended":false,"category":"Personen"},
{"de":"Reicher","tz":"(ma)tajiri","recommended":false,"category":"Personen"},
{"de":"Arbeiter","tz":"mfanya kazi","recommended":false,"category":"Personen"},
{"de":"Bauer","tz":"mkulima","recommended":false,"category":"Personen"},
{"de":"Wachmann","tz":"mlinzi","recommended":false,"category":"Personen"},
{"de":"Einbrecher","tz":"kibaka","recommended":false,"category":"Personen"},
{"de":"(mein) Freund, Kamerad","tz":"mwenzangu","recommended":true,"category":"Personen"},
{"de":"Direktor","tz":"mkurungenzi","recommended":false,"category":"Personen"},
{"de":"Schulleiter, Rektor","tz":"mwalimu mkuu","recommended":false,"category":"Personen"},
{"de":"Dieb","tz":"mwizi","recommended":false,"category":"Personen"},
{"de":"Boss, Chef","tz":"bossi","recommended":false,"category":"Personen"},
{"de":"Anführer, Leiter","tz":"kiongozi","recommended":false,"category":"Personen"},
{"de":"Restaurant","tz":"mgahawa","recommended":true,"category":"Essen"},
{"de":"Ingwer","tz":"tangawizi","recommended":false,"category":"Essen"},
{"de":"Geschirr","tz":"vyombo","recommended":false,"category":"Essen"},
{"de":"Cashews","tz":"korosho","recommended":false,"category":"Essen"},
{"de":"Erdnüsse","tz":"karanga","recommended":false,"category":"Essen"},
{"de":"Saft","tz":"juisi","recommended":false,"category":"Essen"},
{"de":"Tomate","tz":"nyanya","recommended":false,"category":"Essen"},
{"de":"Tasse","tz":"kikombe","recommended":false,"category":"Essen"},
{"de":"Gabel","tz":"uma","recommended":true,"category":"Essen"},
{"de":"Messer","tz":"kisu","recommended":true,"category":"Essen"},
{"de":"Alkohol","tz":"pombe","recommended":true,"category":"Essen"},
{"de":"Küche / Herd / Ofen","tz":"jiko","recommended":true,"category":"Essen"},
{"de":"Flasche","tz":"chupa","recommended":false,"category":"Essen"},
{"de":"Kuchen","tz":"keki","recommended":false,"category":"Essen"},
{"de":"Tomate","tz":"nyanya","recommended":true,"category":"Essen"},
{"de":"Apfel","tz":"epo","recommended":true,"category":"Essen"},
{"de":"Orange","tz":"(ma)chungwa","recommended":false,"category":"Essen"},
{"de":"Ei","tz":"(ma)yai","recommended":true,"category":"Essen"},
{"de":"Papaya","tz":"papai","recommended":false,"category":"Essen"},
{"de":"Zwiebeln","tz":"vitunguu","recommended":false,"category":"Essen"},
{"de":"Kartoffeln","tz":"viazi","recommended":true,"category":"Essen"},
{"de":"Pizza","tz":"piza","recommended":false,"category":"Essen"},
{"de":"Bier","tz":"bia","recommended":true,"category":"Essen"},
{"de":"Tee","tz":"chai","recommended":true,"category":"Essen"},
{"de":"Mais-Pampe","tz":"Ugali","recommended":true,"category":"Essen"},
{"de":"Suppe","tz":"supu","recommended":true,"category":"Essen"},
{"de":"Nudeln","tz":"tambi","recommended":false,"category":"Essen"},
{"de":"Guaven","tz":"mapera","recommended":false,"category":"Essen"},
{"de":"Pommes-Omlett","tz":"chipsy mayai","recommended":true,"category":"Essen"},
{"de":"Banane","tz":"ndizi","recommended":true,"category":"Essen"},
{"de":"Essen","tz":"chakula","recommended":true,"category":"Essen"},
{"de":"Markt","tz":"soko","recommended":true,"category":"Essen"},
{"de":"Frucht","tz":"(ma)tunda","recommended":true,"category":"Essen"},
{"de":"Milch/Brüste","tz":"maziwa","recommended":false,"category":"Essen"},
{"de":"Kaffee","tz":"kahawa","recommended":true,"category":"Essen"},
{"de":"Fleischspieße","tz":"mishkake","recommended":false,"category":"Essen"},
{"de":"Kokosnuss","tz":"nazi","recommended":false,"category":"Essen"},
{"de":"Fisch","tz":"samaki","recommended":false,"category":"Essen"},
{"de":"Nelken","tz":"karafu","recommended":false,"category":"Essen"},
{"de":"Woche","tz":"wiki","recommended":true,"category":"Zeit"},
{"de":"Datum","tz":"tarehe","recommended":false,"category":"Zeit"},
{"de":"Monat","tz":"mwezi","recommended":true,"category":"Zeit"},
{"de":"Jahr","tz":"mwaka","recommended":true,"category":"Zeit"},
{"de":"Tag","tz":"siku","recommended":true,"category":"Zeit"},
{"de":"Nacht","tz":"usiku","recommended":true,"category":"Zeit"},
{"de":"Morgen","tz":"asubuhi","recommended":true,"category":"Zeit"},
{"de":"Mittag/Nachmittag","tz":"mchana","recommended":true,"category":"Zeit"},
{"de":"Abend","tz":"jioni","recommended":true,"category":"Zeit"},
{"de":"Samstag","tz":"jumamosi","recommended":true,"category":"Zeit"},
{"de":"Sonntag","tz":"jumapili","recommended":true,"category":"Zeit"},
{"de":"Montag","tz":"jumatatu","recommended":true,"category":"Zeit"},
{"de":"Dienstag","tz":"jumanne","recommended":true,"category":"Zeit"},
{"de":"Mittwoch","tz":"jumatano","recommended":true,"category":"Zeit"},
{"de":"Donnerstag","tz":"alhamisi","recommended":true,"category":"Zeit"},
{"de":"Freitag","tz":"ijumaa","recommended":true,"category":"Zeit"},
{"de":"über","tz":"juu","recommended":true,"category":"Präpositionen"},
{"de":"unter","tz":"chini","recommended":true,"category":"Präpositionen"},
{"de":"neben/nah","tz":"karibu","recommended":true,"category":"Präpositionen"},
{"de":"vor","tz":"mbele","recommended":true,"category":"Präpositionen"},
{"de":"hinter","tz":"nyuma","recommended":true,"category":"Präpositionen"},
{"de":"fern","tz":"mbali","recommended":false,"category":"Präpositionen"},
{"de":"entlang","tz":"kando","recommended":false,"category":"Präpositionen"},
{"de":"drinnen","tz":"ndani","recommended":true,"category":"Präpositionen"},
{"de":"draußen","tz":"nje","recommended":true,"category":"Präpositionen"},
{"de":"daneben","tz":"pembeni","recommended":true,"category":"Präpositionen"},
{"de":"(Wahl) zwischen","tz":"kati ya","recommended":false,"category":"Präpositionen"},
{"de":"(örtlich) zwischen","tz":"katikati","recommended":false,"category":"Präpositionen"},
{"de":"rechts","tz":"kulia","recommended":true,"category":"Präpositionen"},
{"de":"links","tz":"kushoto","recommended":true,"category":"Präpositionen"},
{"de":"geradeaus","tz":"moja kwa moja","recommended":true,"category":"Präpositionen"},
{"de":"anstatt (mir)","tz":"badala (yangu)","recommended":false,"category":"Präpositionen"},
{"de":"(zeitlich) danach","tz":"baada ya","recommended":false,"category":"Präpositionen"},
{"de":"(zeitlich) davor","tz":"kabla ya","recommended":false,"category":"Präpositionen"},
{"de":"eins (1)","tz":"moja","recommended":true,"category":"Zahlen"},
{"de":"zwei (2)","tz":"mbili","recommended":true,"category":"Zahlen"},
{"de":"drei (3)","tz":"tatu","recommended":true,"category":"Zahlen"},
{"de":"vier (4)","tz":"nne","recommended":true,"category":"Zahlen"},
{"de":"fünf (5)","tz":"tano","recommended":true,"category":"Zahlen"},
{"de":"sechs (6)","tz":"sita","recommended":true,"category":"Zahlen"},
{"de":"sieben (7)","tz":"saba","recommended":true,"category":"Zahlen"},
{"de":"acht (8)","tz":"nane","recommended":true,"category":"Zahlen"},
{"de":"neun (9)","tz":"tisa","recommended":true,"category":"Zahlen"},
{"de":"zehn (10)","tz":"kumi","recommended":true,"category":"Zahlen"},
{"de":"elf (11)","tz":"kumi na moja","recommended":true,"category":"Zahlen"},
{"de":"zwölf (12)","tz":"kumi na mbili","recommended":true,"category":"Zahlen"},
{"de":"dreizehn (13)","tz":"kumi na tatu","recommended":true,"category":"Zahlen"},
{"de":"vierzehn (14)","tz":"kumi na nne","recommended":true,"category":"Zahlen"},
{"de":"fünfzehn (15)","tz":"kumi na tano","recommended":true,"category":"Zahlen"},
{"de":"sechzehn (16)","tz":"kumi na sita","recommended":true,"category":"Zahlen"},
{"de":"siebzehn (17)","tz":"kumi na saba","recommended":true,"category":"Zahlen"},
{"de":"achtzehn (18)","tz":"kumi na nane","recommended":true,"category":"Zahlen"},
{"de":"neunzehn (19)","tz":"kumi na tisa","recommended":true,"category":"Zahlen"},
{"de":"zwanzig (20)","tz":"ishirini","recommended":true,"category":"Zahlen"},
{"de":"dreißig (30)","tz":"thelathini","recommended":false,"category":"Zahlen"},
{"de":"vierzig (40)","tz":"arobaini","recommended":false,"category":"Zahlen"},
{"de":"fünfzig (50)","tz":"hamsini","recommended":false,"category":"Zahlen"},
{"de":"sechzig (60)","tz":"sitini","recommended":false,"category":"Zahlen"},
{"de":"siebzig (70)","tz":"sabini","recommended":false,"category":"Zahlen"},
{"de":"achtzig (80)","tz":"themanini","recommended":false,"category":"Zahlen"},
{"de":"neunzig (90)","tz":"tisini","recommended":false,"category":"Zahlen"},
{"de":"hundert (100)","tz":"mia moja","recommended":true,"category":"Zahlen"},
{"de":"zweihundert (200)","tz":"mia mbili","recommended":true,"category":"Zahlen"},
{"de":"tausend (1000)","tz":"elfu moja","recommended":true,"category":"Zahlen"},
{"de":"hundert tausend (100 000)","tz":"laki moja","recommended":false,"category":"Zahlen"},
{"de":"eine Million (1 000 000)","tz":"milioni","recommended":false,"category":"Zahlen"}
]